#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "✨ Running pre-commit hooks..."
npx lint-staged || { echo "❌ Lint or Prettier failed! Fix it before commit." ; exit 1; }
echo "✅ All good, committing..."
